repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.0"
    hooks:
      - id: ruff
        args: [., --fix, --exit-non-zero-on-fix]
        pass_filenames: false
      - id: ruff-format
        args: [.]
        pass_filenames: false

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.12.1" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: mypy
  #       pass_filenames: false
  #       args: ["--config-file=pyproject.toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
        exclude: .*\.snap$
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v3.6.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow
