repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.12.8"
    hooks:
      - id: ruff
        args: [., --fix, --exit-non-zero-on-fix]
        pass_filenames: false
      - id: ruff-format
        args: [.]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
        exclude: .*\.snap$
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
        exclude: crates/ruff_python_parser.*
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow
