from ast import AST

class Token:
    start: int
    end: int

    @property
    def type(self) -> str: ...
    @property
    def kind(self) -> str: ...

def parse_file(path: str) -> AST: ...
def parse_string(src: str, file_name: str | None = None) -> AST: ...
def lex_string(src: str) -> list[Token]: ...
