[build]
rustflags = ["-Z", "threads=8"]
#rustc-wrapper = "sccache"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
#opt-level = 1
# codegen-backend = "cranelift"
debug = true
# Optional: Additional Cranelift-specific flags for dev profile
# rustflags = ["-Zcodegen-backend=cranelift"]
# # Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
# codegen-backend = "llvm"

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"
