name: Run benchmark tests
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache/benchmark
          key: ${{ runner.os }}-benchmark
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: install project dependencies
        run: uv sync --frozen --no-install-project
      - uses: actions/download-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: dist
      - name: install project wheel
        run: uv pip install xonsh_rd_parser --find-links dist
      - name: run benchmarks with pytest
        run: pytest tests/bench.py --benchmark-json output.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "pytest"
          output-file-path: output.json
          external-data-json-path: ./cache/benchmark/data.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
          summary-always: true
